version: '3.8'

services:
  nextjs:
    image: trungho6959/web-user:v1.1
    build: .
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: production
